### PR TITLE
log progress and contributors each time we perform update #5 #6

### PR DESCRIPTION
**Pull request by Hagellach37**

### CODE REVIEW

**Comment by Hagellach37** [comment]
no, everything is active now. If you want to test comment the parts. You just have to care about the set_in_firebase functions

**Comment by maze2point0** [comment]
Done. Took me a while to get the config work local, now I stuck with that in the logs: 03-06 19:33:04 DEBUG    Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
03-06 19:33:04 DEBUG    [b'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjUwNDk4ZTU3ZjY3YmU4ODcxNzQ3NDU5ZGFmNDcyYzA3MWFkOTljZGUifQ', b'eyJhdWQiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvdG9rZW4iLCJzY29wZSI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZmlyZWJhc2UuZGF0YWJhc2UgaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC91c2VyaW5mby5lbWFpbCBodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2Nsb3VkLXBsYXRmb3JtIiwiaWF0IjoxNTIwMzYxMTg0LCJleHAiOjE1MjAzNjQ3ODQsImlzcyI6ImZpcmViYXNlLWFkbWluc2RrLW95bTVsQG1zZi1tYXBzd2lwZS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSJ9', b'G4jrO1unPVDJgSgY_FitZ6o51qGtQGxJ91I8JeXuecf4uvcQpTCHPJCb0B6X-3nHpf4YbLZmwWcDbW4hoc_3Mm5iAAFuwaNrvpEwNLxeALaPN9S5KcFbsK7SIsXR6eDkIA2bKqR-GAgrUOiq_WqFjMlIs0aTCMaKuHM1rPVZFuZsq4DWcw3w1KA-Etkk2zi1r7Z0T3RTPrCksz2poYi_HTPicfiPLR-jFHqWLMBwi9XQ3nvn01nwQPWPHDk9701udRKcZ1gTdSQp7UVggKzNFDHNCX0Ux3CA-iT6jjHbwzT4TjO16Jbn-N6kFzH032axhgw_NYytU3uBOyE5KhfHeA']
03-06 19:33:04 INFO     Refreshing access_token

Any idea?

**Comment by Hagellach37** [comment]
try to reduce the number of threads, when downloading the progress

**Comment by Hagellach37** [comment]
I think this log is not a problem actually, It just says, that it need to refresh the access token, but then everything else should go fine. What's your opinion. @maze2point0

**Comment by maze2point0** [comment]
I waited a couple of seconds, nothing happened. Reducing the number of threads worked out.
So my local test was successful. Think it's time to test it on the server. 
Any expectations on the rise in costs due to traffic when increasing the update interval?

**Comment by Hagellach37** [comment]
costs will only rise little, the biggest part of our costs come from things that will not change. However we can have a look at this. In google cloud we store all billing information on a daily basis. We will see if something changes and can intervene fast.

**Pull request merged**
